const List<Map<String, dynamic>> clubs = [
  // ── Premier League ──────────────────────────────────────
  {
    'name': 'Arsenal',
    'shortName': 'ARS',
    'league': 'Premier League',
    'country': 'England',
    'color': '#EF0107',
  },
  {
    'name': 'Aston Villa',
    'shortName': 'AVL',
    'league': 'Premier League',
    'country': 'England',
    'color': '#95BFE5',
  },
  {
    'name': 'Brentford',
    'shortName': 'BRE',
    'league': 'Premier League',
    'country': 'England',
    'color': '#E30613',
  },
  {
    'name': 'Brighton',
    'shortName': 'BHA',
    'league': 'Premier League',
    'country': 'England',
    'color': '#0057B8',
  },
  {
    'name': 'Chelsea',
    'shortName': 'CHE',
    'league': 'Premier League',
    'country': 'England',
    'color': '#034694',
  },
  {
    'name': 'Crystal Palace',
    'shortName': 'CRY',
    'league': 'Premier League',
    'country': 'England',
    'color': '#1B458F',
  },
  {
    'name': 'Everton',
    'shortName': 'EVE',
    'league': 'Premier League',
    'country': 'England',
    'color': '#003399',
  },
  {
    'name': 'Fulham',
    'shortName': 'FUL',
    'league': 'Premier League',
    'country': 'England',
    'color': '#CC0000',
  },
  {
    'name': 'Liverpool',
    'shortName': 'LIV',
    'league': 'Premier League',
    'country': 'England',
    'color': '#C8102E',
  },
  {
    'name': 'Man City',
    'shortName': 'MCI',
    'league': 'Premier League',
    'country': 'England',
    'color': '#6CABDD',
  },
  {
    'name': 'Man United',
    'shortName': 'MUN',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DA291C',
  },
  {
    'name': 'Newcastle',
    'shortName': 'NEW',
    'league': 'Premier League',
    'country': 'England',
    'color': '#241F20',
  },
  {
    'name': 'Nottm Forest',
    'shortName': 'NFO',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DD0000',
  },
  {
    'name': 'Tottenham',
    'shortName': 'TOT',
    'league': 'Premier League',
    'country': 'England',
    'color': '#132257',
  },
  {
    'name': 'West Ham',
    'shortName': 'WHU',
    'league': 'Premier League',
    'country': 'England',
    'color': '#7A263A',
  },
  {
    'name': 'Wolves',
    'shortName': 'WOL',
    'league': 'Premier League',
    'country': 'England',
    'color': '#FDB913',
  },

  // ── La Liga ─────────────────────────────────────────────
  {
    'name': 'Athletic Bilbao',
    'shortName': 'ATH',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#EE2523',
  },
  {
    'name': 'Atletico Madrid',
    'shortName': 'ATM',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CB3524',
  },
  {
    'name': 'Barcelona',
    'shortName': 'BAR',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#A50044',
  },
  {
    'name': 'Betis',
    'shortName': 'BET',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#00954C',
  },
  {
    'name': 'Celta Vigo',
    'shortName': 'CEL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#8BBCE4',
  },
  {
    'name': 'Getafe',
    'shortName': 'GET',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#005999',
  },
  {
    'name': 'Girona',
    'shortName': 'GIR',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CD1421',
  },
  {
    'name': 'Osasuna',
    'shortName': 'OSA',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#D2112B',
  },
  {
    'name': 'Real Madrid',
    'shortName': 'RMA',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FEBE10',
  },
  {
    'name': 'Real Sociedad',
    'shortName': 'RSO',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0067A5',
  },
  {
    'name': 'Sevilla',
    'shortName': 'SEV',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#D4011D',
  },
  {
    'name': 'Valencia',
    'shortName': 'VAL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#F5A000',
  },
  {
    'name': 'Villarreal',
    'shortName': 'VIL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FFDD00',
  },

  // ── Serie A ─────────────────────────────────────────────
  {
    'name': 'AC Milan',
    'shortName': 'MIL',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FB090B',
  },
  {
    'name': 'Atalanta',
    'shortName': 'ATA',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#1E4296',
  },
  {
    'name': 'Bologna',
    'shortName': 'BOL',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#9B1932',
  },
  {
    'name': 'Fiorentina',
    'shortName': 'FIO',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#4B0082',
  },
  {
    'name': 'Inter Milan',
    'shortName': 'INT',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#010E80',
  },
  {
    'name': 'Juventus',
    'shortName': 'JUV',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
  },
  {
    'name': 'Lazio',
    'shortName': 'LAZ',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#87D8F7',
  },
  {
    'name': 'Napoli',
    'shortName': 'NAP',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#12A0C3',
  },
  {
    'name': 'AS Roma',
    'shortName': 'ROM',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#8E1F2F',
  },
  {
    'name': 'Torino',
    'shortName': 'TOR',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#731012',
  },

  // ── Bundesliga ──────────────────────────────────────────
  {
    'name': 'Bayer Leverkusen',
    'shortName': 'B04',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E32221',
  },
  {
    'name': 'Bayern Munich',
    'shortName': 'BAY',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#DC052D',
  },
  {
    'name': 'Borussia Dortmund',
    'shortName': 'BVB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#FDE100',
  },
  {
    'name': "Borussia M'gladbach",
    'shortName': 'BMG',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#000000',
  },
  {
    'name': 'Eintracht Frankfurt',
    'shortName': 'SGE',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E1000F',
  },
  {
    'name': 'Freiburg',
    'shortName': 'SCF',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E8001C',
  },
  {
    'name': 'Hoffenheim',
    'shortName': 'TSG',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#1961AC',
  },
  {
    'name': 'RB Leipzig',
    'shortName': 'RBL',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#DD0741',
  },
  {
    'name': 'Stuttgart',
    'shortName': 'VFB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E32219',
  },
  {
    'name': 'Wolfsburg',
    'shortName': 'WOB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#65B32E',
  },

  // ── Ligue 1 ─────────────────────────────────────────────
  {
    'name': 'Lens',
    'shortName': 'LEN',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#FFD700',
  },
  {
    'name': 'Lille',
    'shortName': 'LIL',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#EE1C25',
  },
  {
    'name': 'Lyon',
    'shortName': 'OL',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#0055A4',
  },
  {
    'name': 'Marseille',
    'shortName': 'OM',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#2FAEE0',
  },
  {
    'name': 'Monaco',
    'shortName': 'MON',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#D4011D',
  },
  {
    'name': 'Montpellier',
    'shortName': 'MTP',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#F37020',
  },
  {
    'name': 'Nice',
    'shortName': 'NIC',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#000000',
  },
  {
    'name': 'PSG',
    'shortName': 'PSG',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#004170',
  },
  {
    'name': 'Rennes',
    'shortName': 'REN',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#E5001B',
  },
  {
    'name': 'Strasbourg',
    'shortName': 'RCS',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#0055A4',
  },
];
