const List<Map<String, dynamic>> clubs = [
  // ── Premier League (20 clubs) ───────────────────────────
  {
    'name': 'Arsenal',
    'shortName': 'ARS',
    'nickname': 'The Gunners',
    'league': 'Premier League',
    'country': 'England',
    'color': '#EF0107',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png',
  },
  {
    'name': 'Aston Villa',
    'shortName': 'AVL',
    'nickname': 'The Villans',
    'league': 'Premier League',
    'country': 'England',
    'color': '#95BFE5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png',
  },
  {
    'name': 'Bournemouth',
    'shortName': 'BOU',
    'nickname': 'The Cherries',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DA291C',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/y08nak1534071116.png',
  },
  {
    'name': 'Brentford',
    'shortName': 'BRE',
    'nickname': 'The Bees',
    'league': 'Premier League',
    'country': 'England',
    'color': '#E30613',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png',
  },
  {
    'name': 'Brighton',
    'shortName': 'BHA',
    'nickname': 'The Seagulls',
    'league': 'Premier League',
    'country': 'England',
    'color': '#0057B8',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ywypts1448810904.png',
  },
  {
    'name': 'Chelsea',
    'shortName': 'CHE',
    'nickname': 'The Blues',
    'league': 'Premier League',
    'country': 'England',
    'color': '#034694',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png',
  },
  {
    'name': 'Crystal Palace',
    'shortName': 'CRY',
    'nickname': 'The Eagles',
    'league': 'Premier League',
    'country': 'England',
    'color': '#1B458F',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png',
  },
  {
    'name': 'Everton',
    'shortName': 'EVE',
    'nickname': 'The Toffees',
    'league': 'Premier League',
    'country': 'England',
    'color': '#003399',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png',
  },
  {
    'name': 'Fulham',
    'shortName': 'FUL',
    'nickname': 'The Cottagers',
    'league': 'Premier League',
    'country': 'England',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png',
  },
  {
    'name': 'Ipswich Town',
    'shortName': 'IPS',
    'nickname': 'The Tractor Boys',
    'league': 'Premier League',
    'country': 'England',
    'color': '#0044A9',
    'badgeUrl': '',
  },
  {
    'name': 'Leicester City',
    'shortName': 'LEI',
    'nickname': 'The Foxes',
    'league': 'Premier League',
    'country': 'England',
    'color': '#003090',
    'badgeUrl': '',
  },
  {
    'name': 'Liverpool',
    'shortName': 'LIV',
    'nickname': 'The Reds',
    'league': 'Premier League',
    'country': 'England',
    'color': '#C8102E',
    'badgeUrl': '',
  },
  {
    'name': 'Man City',
    'shortName': 'MCI',
    'nickname': 'The Citizens',
    'league': 'Premier League',
    'country': 'England',
    'color': '#6CABDD',
    'badgeUrl': '',
  },
  {
    'name': 'Man United',
    'shortName': 'MUN',
    'nickname': 'The Red Devils',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DA291C',
    'badgeUrl': '',
  },
  {
    'name': 'Newcastle',
    'shortName': 'NEW',
    'nickname': 'The Magpies',
    'league': 'Premier League',
    'country': 'England',
    'color': '#241F20',
    'badgeUrl': '',
  },
  {
    'name': 'Nottm Forest',
    'shortName': 'NFO',
    'nickname': 'The Tricky Trees',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DD0000',
    'badgeUrl': '',
  },
  {
    'name': 'Southampton',
    'shortName': 'SOU',
    'nickname': 'The Saints',
    'league': 'Premier League',
    'country': 'England',
    'color': '#D71920',
    'badgeUrl': '',
  },
  {
    'name': 'Tottenham',
    'shortName': 'TOT',
    'nickname': 'Spurs',
    'league': 'Premier League',
    'country': 'England',
    'color': '#132257',
    'badgeUrl': '',
  },
  {
    'name': 'West Ham',
    'shortName': 'WHU',
    'nickname': 'The Hammers',
    'league': 'Premier League',
    'country': 'England',
    'color': '#7A263A',
    'badgeUrl': '',
  },
  {
    'name': 'Wolves',
    'shortName': 'WOL',
    'nickname': 'The Wolves',
    'league': 'Premier League',
    'country': 'England',
    'color': '#FDB913',
    'badgeUrl': '',
  },

  // ── La Liga (20 clubs) ──────────────────────────────────
  {
    'name': 'Alaves',
    'shortName': 'ALA',
    'nickname': 'El Glorioso',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0070B8',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/mfn99h1734673842.png',
  },
  {
    'name': 'Athletic Bilbao',
    'shortName': 'ATH',
    'nickname': 'Los Leones',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#EE2523',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/68w7fe1639408210.png',
  },
  {
    'name': 'Atletico Madrid',
    'shortName': 'ATM',
    'nickname': 'Los Colchoneros',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CB3524',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/0ulh3q1719984315.png',
  },
  {
    'name': 'Barcelona',
    'shortName': 'BAR',
    'nickname': 'Blaugrana',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#A50044',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/wq9sir1639406443.png',
  },
  {
    'name': 'Betis',
    'shortName': 'BET',
    'nickname': 'Los Verdiblancos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#00954C',
    'badgeUrl': '',
  },
  {
    'name': 'Celta Vigo',
    'shortName': 'CEL',
    'nickname': 'Os Celestes',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#8BBCE4',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png',
  },
  {
    'name': 'Espanyol',
    'shortName': 'ESP',
    'nickname': 'Los Pericos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0070B8',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/867nzz1681703222.png',
  },
  {
    'name': 'Getafe',
    'shortName': 'GET',
    'nickname': 'Los Azulones',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#005999',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/eyh2891655594452.png',
  },
  {
    'name': 'Girona',
    'shortName': 'GIR',
    'nickname': 'Els Vermells',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CD1421',
    'badgeUrl': '',
  },
  {
    'name': 'Las Palmas',
    'shortName': 'LPA',
    'nickname': 'Los Amarillos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Leganes',
    'shortName': 'LEG',
    'nickname': 'El Pepinero',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#003DA5',
    'badgeUrl': '',
  },
  {
    'name': 'Mallorca',
    'shortName': 'MAL',
    'nickname': 'Los Bermellones',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#C8102E',
    'badgeUrl': '',
  },
  {
    'name': 'Osasuna',
    'shortName': 'OSA',
    'nickname': 'Los Rojillos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#D2112B',
    'badgeUrl': '',
  },
  {
    'name': 'Rayo Vallecano',
    'shortName': 'RAY',
    'nickname': 'Los Franjirrojos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Real Madrid',
    'shortName': 'RMA',
    'nickname': 'Los Blancos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FEBE10',
    'badgeUrl': '',
  },
  {
    'name': 'Real Sociedad',
    'shortName': 'RSO',
    'nickname': 'La Real',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0067A5',
    'badgeUrl': '',
  },
  {
    'name': 'Real Valladolid',
    'shortName': 'VLD',
    'nickname': 'Los Pucelanos',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#6A0DAD',
    'badgeUrl': '',
  },
  {
    'name': 'Sevilla',
    'shortName': 'SEV',
    'nickname': 'Los Nervionenses',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#D4011D',
    'badgeUrl': '',
  },
  {
    'name': 'Valencia',
    'shortName': 'VAL',
    'nickname': 'Los Che',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#F5A000',
    'badgeUrl': '',
  },
  {
    'name': 'Villarreal',
    'shortName': 'VIL',
    'nickname': 'The Yellow Submarine',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FFDD00',
    'badgeUrl': '',
  },

  // ── Serie A (20 clubs) ──────────────────────────────────
  {
    'name': 'AC Milan',
    'shortName': 'MIL',
    'nickname': 'Rossoneri',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FB090B',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/wvspur1448806617.png',
  },
  {
    'name': 'Atalanta',
    'shortName': 'ATA',
    'nickname': 'La Dea',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#1E4296',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/qix5ku1780561327.png',
  },
  {
    'name': 'Bologna',
    'shortName': 'BOL',
    'nickname': 'Rossoblu',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#9B1932',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png',
  },
  {
    'name': 'Cagliari',
    'shortName': 'CAG',
    'nickname': 'Rossoblù',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/wvsvxt1447534471.png',
  },
  {
    'name': 'Como',
    'shortName': 'COM',
    'nickname': 'Lariani',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#003DA5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/02x81t1627405841.png',
  },
  {
    'name': 'Empoli',
    'shortName': 'EMP',
    'nickname': 'Gli Azzurri',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#0070B8',
    'badgeUrl': '',
  },
  {
    'name': 'Fiorentina',
    'shortName': 'FIO',
    'nickname': 'La Viola',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#4B0082',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/hc8nhu1656098030.png',
  },
  {
    'name': 'Genoa',
    'shortName': 'GEN',
    'nickname': 'Grifone',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/52s8dn1655553600.png',
  },
  {
    'name': 'Hellas Verona',
    'shortName': 'HEL',
    'nickname': 'Gialloblu',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Inter Milan',
    'shortName': 'INT',
    'nickname': 'Nerazzurri',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#010E80',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ryhu6d1617113103.png',
  },
  {
    'name': 'Juventus',
    'shortName': 'JUV',
    'nickname': 'The Old Lady',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/uxf0gr1742983727.png',
  },
  {
    'name': 'Lazio',
    'shortName': 'LAZ',
    'nickname': 'Biancocelesti',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#87D8F7',
    'badgeUrl': '',
  },
  {
    'name': 'Lecce',
    'shortName': 'LEC',
    'nickname': 'Giallorossi',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Monza',
    'shortName': 'MOZ',
    'nickname': 'Biancorossi',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Napoli',
    'shortName': 'NAP',
    'nickname': 'Gli Azzurri',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#12A0C3',
    'badgeUrl': '',
  },
  {
    'name': 'Parma',
    'shortName': 'PAR',
    'nickname': 'Crociati',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'AS Roma',
    'shortName': 'ROM',
    'nickname': 'I Giallorossi',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#8E1F2F',
    'badgeUrl': '',
  },
  {
    'name': 'Torino',
    'shortName': 'TOR',
    'nickname': 'Il Toro',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#731012',
    'badgeUrl': '',
  },
  {
    'name': 'Udinese',
    'shortName': 'UDI',
    'nickname': 'Bianconeri',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
    'badgeUrl': '',
  },
  {
    'name': 'Venezia',
    'shortName': 'VEN',
    'nickname': 'Arancioneroverdi',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
    'badgeUrl': '',
  },

  // ── Bundesliga (18 clubs) ───────────────────────────────
  {
    'name': 'Augsburg',
    'shortName': 'AUG',
    'nickname': 'Die Fuggerstädter',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#BA3733',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xqyyvq1473453233.png',
  },
  {
    'name': 'Bayer Leverkusen',
    'shortName': 'B04',
    'nickname': 'Die Werkself',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E32221',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/3x9k851726760113.png',
  },
  {
    'name': 'Bayern Munich',
    'shortName': 'BAY',
    'nickname': 'Die Roten',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#DC052D',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/01ogkh1716960412.png',
  },
  {
    'name': 'Bochum',
    'shortName': 'BOC',
    'nickname': 'Die Unabsteigbaren',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#005CA9',
    'badgeUrl': '',
  },
  {
    'name': 'Borussia Dortmund',
    'shortName': 'BVB',
    'nickname': 'Die Schwarzgelben',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#FDE100',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/tqo8ge1716960353.png',
  },
  {
    'name': "Borussia M'gladbach",
    'shortName': 'BMG',
    'nickname': 'Die Fohlen',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/sysurw1473453380.png',
  },
  {
    'name': 'Eintracht Frankfurt',
    'shortName': 'SGE',
    'nickname': 'Die Adler',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E1000F',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png',
  },
  {
    'name': 'Freiburg',
    'shortName': 'SCF',
    'nickname': 'Die Breisgauer',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E8001C',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/urwtup1473453288.png',
  },
  {
    'name': 'Hamburg',
    'shortName': 'HSV',
    'nickname': 'Die Rothosen',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#003FA3',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/tvtppt1473453296.png',
  },
  {
    'name': 'Hoffenheim',
    'shortName': 'TSG',
    'nickname': 'Die Kraichgauer',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#1961AC',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/9hwvb21621593919.png',
  },
  {
    'name': 'Holstein Kiel',
    'shortName': 'KIE',
    'nickname': 'Die Störche',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#C8102E',
    'badgeUrl': '',
  },
  {
    'name': 'Mainz',
    'shortName': 'MAI',
    'nickname': 'Die Nullfünfer',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'RB Leipzig',
    'shortName': 'RBL',
    'nickname': 'Die Roten Bullen',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#DD0741',
    'badgeUrl': '',
  },
  {
    'name': 'St. Pauli',
    'shortName': 'STP',
    'nickname': 'Die Kiezkicker',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#8B3A3A',
    'badgeUrl': '',
  },
  {
    'name': 'Stuttgart',
    'shortName': 'VFB',
    'nickname': 'Die Schwaben',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E32219',
    'badgeUrl': '',
  },
  {
    'name': 'Union Berlin',
    'shortName': 'UNB',
    'nickname': 'Die Eisernen',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Werder Bremen',
    'shortName': 'WER',
    'nickname': 'Die Grün-Weißen',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#1D9A4E',
    'badgeUrl': '',
  },
  {
    'name': 'Wolfsburg',
    'shortName': 'WOB',
    'nickname': 'Die Wölfe',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#65B32E',
    'badgeUrl': '',
  },

  // ── Ligue 1 (18 clubs) ──────────────────────────────────
  {
    'name': 'Angers',
    'shortName': 'ANG',
    'nickname': 'Le SCO',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ix6q4w1678808069.png',
  },
  {
    'name': 'Auxerre',
    'shortName': 'AUX',
    'nickname': 'Les Auxerrois',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#003DA5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/lzdtbf1658753355.png',
  },
  {
    'name': 'Brest',
    'shortName': 'BRE',
    'nickname': 'Les Pirates',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/z69be41598797026.png',
  },
  {
    'name': 'Le Havre',
    'shortName': 'HAV',
    'nickname': 'Les Ciel et Marine',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#003DA5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/aikowk1546475003.png',
  },
  {
    'name': 'Lens',
    'shortName': 'LEN',
    'nickname': 'Sang et Or',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#FFD700',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/3pxoum1598797195.png',
  },
  {
    'name': 'Lille',
    'shortName': 'LIL',
    'nickname': 'Les Dogues',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#EE1C25',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/2giize1534005340.png',
  },
  {
    'name': 'Lyon',
    'shortName': 'OL',
    'nickname': 'Les Gones',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#0055A4',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/blk9771656932845.png',
  },
  {
    'name': 'Marseille',
    'shortName': 'OM',
    'nickname': 'Les Phocéens',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#2FAEE0',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/c6bazh1779212287.png',
  },
  {
    'name': 'Monaco',
    'shortName': 'MON',
    'nickname': 'Les Rouges et Blancs',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#D4011D',
    'badgeUrl': '',
  },
  {
    'name': 'Montpellier',
    'shortName': 'MTP',
    'nickname': 'La Paillade',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#F37020',
    'badgeUrl': '',
  },
  {
    'name': 'Nantes',
    'shortName': 'NAN',
    'nickname': 'Les Canaris',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Nice',
    'shortName': 'NIC',
    'nickname': 'Les Aiglons',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#000000',
    'badgeUrl': '',
  },
  {
    'name': 'PSG',
    'shortName': 'PSG',
    'nickname': 'Les Parisiens',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#004170',
    'badgeUrl': '',
  },
  {
    'name': 'Reims',
    'shortName': 'REI',
    'nickname': 'Les Rouges et Blancs',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Rennes',
    'shortName': 'REN',
    'nickname': 'Les Rouge et Noir',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#E5001B',
    'badgeUrl': '',
  },
  {
    'name': 'Saint-Etienne',
    'shortName': 'STE',
    'nickname': 'Les Verts',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#1D9A4E',
    'badgeUrl': '',
  },
  {
    'name': 'Strasbourg',
    'shortName': 'RCS',
    'nickname': 'Les Alsaciens',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#0055A4',
    'badgeUrl': '',
  },
  {
    'name': 'Toulouse',
    'shortName': 'TOU',
    'nickname': 'Les Violets',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#6A0DAD',
    'badgeUrl': '',
  },
  // ── Primeira Liga (18 clubs) ───────────────────────────
  {
    'name': 'Alverca',
    'shortName': 'ALV',
    'nickname': 'Os Alverquenses',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/6ljryf1691990098.png',
  },
  {
    'name': 'Arouca',
    'shortName': 'ARO',
    'nickname': 'Os Arouquenses',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#FEF405',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/vgbzjq1628853833.png',
  },
  {
    'name': 'AVS',
    'shortName': 'AVS',
    'nickname': 'Os Vilacondenses',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xp8oqb1688676544.png',
  },
  {
    'name': 'Benfica',
    'shortName': 'BEN',
    'nickname': 'As Águias',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#E83030',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/hj4kyc1781152436.png',
  },
  {
    'name': 'Braga',
    'shortName': 'BRG',
    'nickname': 'Os Arsenalistas',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#C82B20',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/8g4aod1678717261.png',
  },
  {
    'name': 'Casa Pia',
    'shortName': 'CPA',
    'nickname': 'Os Gansos',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/d8ugsc1678717133.png',
  },
  {
    'name': 'Estoril Praia',
    'shortName': 'EST',
    'nickname': 'Os Canarinhos',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#4C4F94',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/lq9h8m1628854051.png',
  },
  {
    'name': 'Estrela Amadora',
    'shortName': 'EAM',
    'nickname': 'Os Tricolores',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#BE3C2C',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/2tx5621626095555.png',
  },
  {
    'name': 'Famalicão',
    'shortName': 'FAM',
    'nickname': 'Os Famalicenses',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#0B3D6B',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/a3f4er1563653256.png',
  },
  {
    'name': 'Gil Vicente',
    'shortName': 'GIL',
    'nickname': 'Os Galos',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#D52929',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/88bsg41626201503.png',
  },
  {
    'name': 'Porto',
    'shortName': 'POR',
    'nickname': 'Os Dragões',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#003DA5',
    'badgeUrl': '',
  },
  {
    'name': 'Sporting CP',
    'shortName': 'SCP',
    'nickname': 'Os Leões',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#006600',
    'badgeUrl': '',
  },
  {
    'name': 'Guimarães',
    'shortName': 'GIM',
    'nickname': 'Os Conquistadores',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#000000',
    'badgeUrl': '',
  },
  {
    'name': 'Moreirense',
    'shortName': 'MOR',
    'nickname': 'Os Cónegos',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#006600',
    'badgeUrl': '',
  },
  {
    'name': 'Rio Ave',
    'shortName': 'RIO',
    'nickname': 'Os Vilacondenses',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#006600',
    'badgeUrl': '',
  },
  {
    'name': 'Boavista',
    'shortName': 'BOA',
    'nickname': 'Os Axadrezados',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#000000',
    'badgeUrl': '',
  },
  {
    'name': 'Santa Clara',
    'shortName': 'SCL',
    'nickname': 'Os Açorianos',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Nacional',
    'shortName': 'NAC',
    'nickname': 'Os Alvinegros',
    'league': 'Primeira Liga',
    'country': 'Portugal',
    'color': '#000000',
    'badgeUrl': '',
  },
];

const List<Map<String, dynamic>> leagues = [
  {
    'name': 'Premier League',
    'country': 'England',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/league/badge/gasy9d1737743125.png',
    'numberOfClubs': 20,
  },
  {
    'name': 'La Liga',
    'country': 'Spain',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/league/badge/ja4it51687628717.png',
    'numberOfClubs': 20,
  },
  {
    'name': 'Serie A',
    'country': 'Italy',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/league/badge/67q3q21679951383.png',
    'numberOfClubs': 20,
  },
  {
    'name': 'Bundesliga',
    'country': 'Germany',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/league/badge/teqh1b1679952008.png',
    'numberOfClubs': 18,
  },
  {
    'name': 'Ligue 1',
    'country': 'France',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/league/badge/9f7z9d1742983155.png',
    'numberOfClubs': 18,
  },
  {
    'name': 'Primeira Liga',
    'country': 'Portugal',
    'badgeUrl': '',
    'numberOfClubs': 18,
  },
];
