const List<Map<String, dynamic>> clubs = [
  // ── Premier League (20 clubs) ───────────────────────────
  {
    'name': 'Arsenal',
    'shortName': 'ARS',
    'league': 'Premier League',
    'country': 'England',
    'color': '#EF0107',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png',
  },
  {
    'name': 'Aston Villa',
    'shortName': 'AVL',
    'league': 'Premier League',
    'country': 'England',
    'color': '#95BFE5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png',
  },
  {
    'name': 'Bournemouth',
    'shortName': 'BOU',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DA291C',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/y08nak1534071116.png',
  },
  {
    'name': 'Brentford',
    'shortName': 'BRE',
    'league': 'Premier League',
    'country': 'England',
    'color': '#E30613',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png',
  },
  {
    'name': 'Brighton',
    'shortName': 'BHA',
    'league': 'Premier League',
    'country': 'England',
    'color': '#0057B8',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ywypts1448810904.png',
  },
  {
    'name': 'Chelsea',
    'shortName': 'CHE',
    'league': 'Premier League',
    'country': 'England',
    'color': '#034694',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/yvwvtu1448813215.png',
  },
  {
    'name': 'Crystal Palace',
    'shortName': 'CRY',
    'league': 'Premier League',
    'country': 'England',
    'color': '#1B458F',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png',
  },
  {
    'name': 'Everton',
    'shortName': 'EVE',
    'league': 'Premier League',
    'country': 'England',
    'color': '#003399',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png',
  },
  {
    'name': 'Fulham',
    'shortName': 'FUL',
    'league': 'Premier League',
    'country': 'England',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png',
  },
  {
    'name': 'Ipswich Town',
    'shortName': 'IPS',
    'league': 'Premier League',
    'country': 'England',
    'color': '#0044A9',
    'badgeUrl': '',
  },
  {
    'name': 'Leicester City',
    'shortName': 'LEI',
    'league': 'Premier League',
    'country': 'England',
    'color': '#003090',
    'badgeUrl': '',
  },
  {
    'name': 'Liverpool',
    'shortName': 'LIV',
    'league': 'Premier League',
    'country': 'England',
    'color': '#C8102E',
    'badgeUrl': '',
  },
  {
    'name': 'Man City',
    'shortName': 'MCI',
    'league': 'Premier League',
    'country': 'England',
    'color': '#6CABDD',
    'badgeUrl': '',
  },
  {
    'name': 'Man United',
    'shortName': 'MUN',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DA291C',
    'badgeUrl': '',
  },
  {
    'name': 'Newcastle',
    'shortName': 'NEW',
    'league': 'Premier League',
    'country': 'England',
    'color': '#241F20',
    'badgeUrl': '',
  },
  {
    'name': 'Nottm Forest',
    'shortName': 'NFO',
    'league': 'Premier League',
    'country': 'England',
    'color': '#DD0000',
    'badgeUrl': '',
  },
  {
    'name': 'Southampton',
    'shortName': 'SOU',
    'league': 'Premier League',
    'country': 'England',
    'color': '#D71920',
    'badgeUrl': '',
  },
  {
    'name': 'Tottenham',
    'shortName': 'TOT',
    'league': 'Premier League',
    'country': 'England',
    'color': '#132257',
    'badgeUrl': '',
  },
  {
    'name': 'West Ham',
    'shortName': 'WHU',
    'league': 'Premier League',
    'country': 'England',
    'color': '#7A263A',
    'badgeUrl': '',
  },
  {
    'name': 'Wolves',
    'shortName': 'WOL',
    'league': 'Premier League',
    'country': 'England',
    'color': '#FDB913',
    'badgeUrl': '',
  },

  // ── La Liga (20 clubs) ──────────────────────────────────
  {
    'name': 'Alaves',
    'shortName': 'ALA',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0070B8',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/mfn99h1734673842.png',
  },
  {
    'name': 'Athletic Bilbao',
    'shortName': 'ATH',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#EE2523',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/68w7fe1639408210.png',
  },
  {
    'name': 'Atletico Madrid',
    'shortName': 'ATM',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CB3524',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/0ulh3q1719984315.png',
  },
  {
    'name': 'Barcelona',
    'shortName': 'BAR',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#A50044',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/wq9sir1639406443.png',
  },
  {
    'name': 'Betis',
    'shortName': 'BET',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#00954C',
    'badgeUrl': '',
  },
  {
    'name': 'Celta Vigo',
    'shortName': 'CEL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#8BBCE4',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png',
  },
  {
    'name': 'Espanyol',
    'shortName': 'ESP',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0070B8',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/867nzz1681703222.png',
  },
  {
    'name': 'Getafe',
    'shortName': 'GET',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#005999',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/eyh2891655594452.png',
  },
  {
    'name': 'Girona',
    'shortName': 'GIR',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CD1421',
    'badgeUrl': '',
  },
  {
    'name': 'Las Palmas',
    'shortName': 'LPA',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Leganes',
    'shortName': 'LEG',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#003DA5',
    'badgeUrl': '',
  },
  {
    'name': 'Mallorca',
    'shortName': 'MAL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#C8102E',
    'badgeUrl': '',
  },
  {
    'name': 'Osasuna',
    'shortName': 'OSA',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#D2112B',
    'badgeUrl': '',
  },
  {
    'name': 'Rayo Vallecano',
    'shortName': 'RAY',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Real Madrid',
    'shortName': 'RMA',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FEBE10',
    'badgeUrl': '',
  },
  {
    'name': 'Real Sociedad',
    'shortName': 'RSO',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#0067A5',
    'badgeUrl': '',
  },
  {
    'name': 'Real Valladolid',
    'shortName': 'VLD',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#6A0DAD',
    'badgeUrl': '',
  },
  {
    'name': 'Sevilla',
    'shortName': 'SEV',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#D4011D',
    'badgeUrl': '',
  },
  {
    'name': 'Valencia',
    'shortName': 'VAL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#F5A000',
    'badgeUrl': '',
  },
  {
    'name': 'Villarreal',
    'shortName': 'VIL',
    'league': 'La Liga',
    'country': 'Spain',
    'color': '#FFDD00',
    'badgeUrl': '',
  },

  // ── Serie A (20 clubs) ──────────────────────────────────
  {
    'name': 'AC Milan',
    'shortName': 'MIL',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FB090B',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/wvspur1448806617.png',
  },
  {
    'name': 'Atalanta',
    'shortName': 'ATA',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#1E4296',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/qix5ku1780561327.png',
  },
  {
    'name': 'Bologna',
    'shortName': 'BOL',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#9B1932',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png',
  },
  {
    'name': 'Cagliari',
    'shortName': 'CAG',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/wvsvxt1447534471.png',
  },
  {
    'name': 'Como',
    'shortName': 'COM',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#003DA5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/02x81t1627405841.png',
  },
  {
    'name': 'Empoli',
    'shortName': 'EMP',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#0070B8',
    'badgeUrl': '',
  },
  {
    'name': 'Fiorentina',
    'shortName': 'FIO',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#4B0082',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/hc8nhu1656098030.png',
  },
  {
    'name': 'Genoa',
    'shortName': 'GEN',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/52s8dn1655553600.png',
  },
  {
    'name': 'Hellas Verona',
    'shortName': 'HEL',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Inter Milan',
    'shortName': 'INT',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#010E80',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ryhu6d1617113103.png',
  },
  {
    'name': 'Juventus',
    'shortName': 'JUV',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/uxf0gr1742983727.png',
  },
  {
    'name': 'Lazio',
    'shortName': 'LAZ',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#87D8F7',
    'badgeUrl': '',
  },
  {
    'name': 'Lecce',
    'shortName': 'LEC',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Monza',
    'shortName': 'MOZ',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Napoli',
    'shortName': 'NAP',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#12A0C3',
    'badgeUrl': '',
  },
  {
    'name': 'Parma',
    'shortName': 'PAR',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'AS Roma',
    'shortName': 'ROM',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#8E1F2F',
    'badgeUrl': '',
  },
  {
    'name': 'Torino',
    'shortName': 'TOR',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#731012',
    'badgeUrl': '',
  },
  {
    'name': 'Udinese',
    'shortName': 'UDI',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
    'badgeUrl': '',
  },
  {
    'name': 'Venezia',
    'shortName': 'VEN',
    'league': 'Serie A',
    'country': 'Italy',
    'color': '#000000',
    'badgeUrl': '',
  },

  // ── Bundesliga (18 clubs) ───────────────────────────────
  {
    'name': 'Augsburg',
    'shortName': 'AUG',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#BA3733',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/xqyyvq1473453233.png',
  },
  {
    'name': 'Bayer Leverkusen',
    'shortName': 'B04',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E32221',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/3x9k851726760113.png',
  },
  {
    'name': 'Bayern Munich',
    'shortName': 'BAY',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#DC052D',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/01ogkh1716960412.png',
  },
  {
    'name': 'Bochum',
    'shortName': 'BOC',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#005CA9',
    'badgeUrl': '',
  },
  {
    'name': 'Borussia Dortmund',
    'shortName': 'BVB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#FDE100',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/tqo8ge1716960353.png',
  },
  {
    'name': "Borussia M'gladbach",
    'shortName': 'BMG',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/sysurw1473453380.png',
  },
  {
    'name': 'Eintracht Frankfurt',
    'shortName': 'SGE',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E1000F',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png',
  },
  {
    'name': 'Freiburg',
    'shortName': 'SCF',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E8001C',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/urwtup1473453288.png',
  },
  {
    'name': 'Hamburg',
    'shortName': 'HSV',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#003FA3',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/tvtppt1473453296.png',
  },
  {
    'name': 'Hoffenheim',
    'shortName': 'TSG',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#1961AC',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/9hwvb21621593919.png',
  },
  {
    'name': 'Holstein Kiel',
    'shortName': 'KIE',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#C8102E',
    'badgeUrl': '',
  },
  {
    'name': 'Mainz',
    'shortName': 'MAI',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'RB Leipzig',
    'shortName': 'RBL',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#DD0741',
    'badgeUrl': '',
  },
  {
    'name': 'St. Pauli',
    'shortName': 'STP',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#8B3A3A',
    'badgeUrl': '',
  },
  {
    'name': 'Stuttgart',
    'shortName': 'VFB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#E32219',
    'badgeUrl': '',
  },
  {
    'name': 'Union Berlin',
    'shortName': 'UNB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Werder Bremen',
    'shortName': 'WER',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#1D9A4E',
    'badgeUrl': '',
  },
  {
    'name': 'Wolfsburg',
    'shortName': 'WOB',
    'league': 'Bundesliga',
    'country': 'Germany',
    'color': '#65B32E',
    'badgeUrl': '',
  },

  // ── Ligue 1 (18 clubs) ──────────────────────────────────
  {
    'name': 'Angers',
    'shortName': 'ANG',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#000000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/ix6q4w1678808069.png',
  },
  {
    'name': 'Auxerre',
    'shortName': 'AUX',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#003DA5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/lzdtbf1658753355.png',
  },
  {
    'name': 'Brest',
    'shortName': 'BRE',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#CC0000',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/z69be41598797026.png',
  },
  {
    'name': 'Le Havre',
    'shortName': 'HAV',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#003DA5',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/aikowk1546475003.png',
  },
  {
    'name': 'Lens',
    'shortName': 'LEN',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#FFD700',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/3pxoum1598797195.png',
  },
  {
    'name': 'Lille',
    'shortName': 'LIL',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#EE1C25',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/2giize1534005340.png',
  },
  {
    'name': 'Lyon',
    'shortName': 'OL',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#0055A4',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/blk9771656932845.png',
  },
  {
    'name': 'Marseille',
    'shortName': 'OM',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#2FAEE0',
    'badgeUrl':
        'https://r2.thesportsdb.com/images/media/team/badge/c6bazh1779212287.png',
  },
  {
    'name': 'Monaco',
    'shortName': 'MON',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#D4011D',
    'badgeUrl': '',
  },
  {
    'name': 'Montpellier',
    'shortName': 'MTP',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#F37020',
    'badgeUrl': '',
  },
  {
    'name': 'Nantes',
    'shortName': 'NAN',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#FFD700',
    'badgeUrl': '',
  },
  {
    'name': 'Nice',
    'shortName': 'NIC',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#000000',
    'badgeUrl': '',
  },
  {
    'name': 'PSG',
    'shortName': 'PSG',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#004170',
    'badgeUrl': '',
  },
  {
    'name': 'Reims',
    'shortName': 'REI',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#CC0000',
    'badgeUrl': '',
  },
  {
    'name': 'Rennes',
    'shortName': 'REN',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#E5001B',
    'badgeUrl': '',
  },
  {
    'name': 'Saint-Etienne',
    'shortName': 'STE',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#1D9A4E',
    'badgeUrl': '',
  },
  {
    'name': 'Strasbourg',
    'shortName': 'RCS',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#0055A4',
    'badgeUrl': '',
  },
  {
    'name': 'Toulouse',
    'shortName': 'TOU',
    'league': 'Ligue 1',
    'country': 'France',
    'color': '#6A0DAD',
    'badgeUrl': '',
  },
];
